### PR TITLE
Game design

### PR DESCRIPTION
**Pull request by Lojdquist**
* Fix button implementation on gamescreen.
* Added icon on gamescreen.
* A little surprise on gamescreen.

### CODE REVIEW

**Comment by Joel-Almqvist** [comment]
Looking at it

**Comment by Lojdquist** [comment]
Buttons changing colors was just a fun feature, didn't know it affected the UI side of the application. Will review this later.

**Comment by Joel-Almqvist** [comment]
Aha so that was the fun surprise you wrote about! It looks funky but I don't think that's what we want up on master sadly :(

**Comment by Lojdquist** [comment]
-- Changes
* Fixed bug with colors changing on UI, button got pressed immediately.
* Added easter egg, If player name contains party, party mode will start
* Added playername to screen.

-- Issuses 
* May not be responsive on all devices, but should look good on majority of devices when in fullscreen. 

-- Should look in to
* Only one button can be pressed at any given time. The way we currently send button data is in an array if multiple buttons would be pressed, but multi-touch does not work => array length will always be one or zero. Maybe better just to send which button has been pressed.

**Comment by Lojdquist** [comment]
A cooldown indicator should also be implemented.

**Pull request merged**
